# Generated by Django 3.2 on 2023-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_choices', models.CharField(choices=[('ACCOMODATION', 'Accomodation'), ('AMENITIES', 'Amentities'), ('MISCELLANOUS', 'Miscellanous')], default='ACCOMODATION', max_length=20)),
                ('sort_number', models.IntegerField()),
                ('title', models.CharField(max_length=150, null=True)),
                ('text', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
