# Generated by Django 3.2 on 2023-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.CharField(blank=True, max_length=200, null=True)),
                ('full_date', models.CharField(blank=True, max_length=200, null=True)),
                ('month_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_display', models.BooleanField()),
            ],
        ),
    ]
