# Generated by Django 3.2 on 2023-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20231114_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datesettings',
            name='annual_rate',
        ),
        migrations.RemoveField(
            model_name='datesettings',
            name='annual_rate_currency',
        ),
    ]
