# Generated by Django 3.2 on 2023-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230918_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpoda',
            name='booking_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='fname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='lname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='notes',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='phone_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='podA',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='podA_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='status',
            field=models.CharField(default='Available', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpoda',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
