# Generated by Django 3.2 on 2023-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230925_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpoda',
            name='arrival_range',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookingpodb',
            name='arrival_range',
            field=models.DateField(null=True),
        ),
    ]
