# Generated by Django 3.2 on 2023-10-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20231004_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpoda',
            name='arrival_range',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpodb',
            name='arrival_range',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
