# Generated by Django 3.2 on 2023-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20231004_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpoda',
            name='eta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
