# Generated by Django 3.2 on 2023-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20231021_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=200, null=True)),
                ('page_url', models.CharField(blank=True, max_length=200, null=True)),
                ('page_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('page_phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
