# Generated by Django 3.2 on 2023-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20231114_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesettings',
            name='annual_rate_currency',
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='annual_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
