# Generated by Django 3.2 on 2023-11-23 19:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookingpoda_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpodb',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
