# Generated by Django 3.2 on 2023-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20231214_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsettings',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
