# Generated by Django 3.2 on 2023-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('podArate', models.CharField(default='80', max_length=10)),
                ('podAstatus', models.CharField(max_length=150, null=True)),
                ('podBrate', models.CharField(default='80', max_length=10)),
                ('podBstatus', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PodAAvailability',
        ),
        migrations.DeleteModel(
            name='PodBAvailability',
        ),
    ]
